_ca5‍.x([["default",()=>_ca5‍.o]]);_ca5‍.d(errorHandler = (fn) =>
    (req, res, next) => {
        Promise.resolve(fn(req, res, next))
            .catch(next);
    });